server.port: 8080
spring.application.name: user-service
spring:
  main:
    lazy-initialization : true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


spring.jpa:
  hibernate.ddl-auto: none
  show-sql: false


spring.liquibase:
  change-log: classpath:config/liquibase/db.changelog-master.xml
  contexts: dev




