server.port: 2019
spring.application.name: user-service


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: {POSTGRES_USER} #postgresUser
    password: {POSTGRES_PASSWORD} #postgresPW
    hikari:
      initialization-fail-timeout: 0



spring.jpa:
  hibernate.ddl-auto: none
  show-sql: false


spring.liquibase:
  change-log: classpath:config/liquibase/db.changelog-master.xml
  contexts: dev




